<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <title>Award Letter {{ $award->award_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 13px; margin: 40px; }
        h1 { font-size: 22px; color: #1e3a8a; margin-bottom: 4px; }
        h2 { font-size: 15px; margin: 24px 0 8px; }
        .muted { color: #64748b; font-size: 11px; }
        .box { border: 1px solid #cbd5e1; padding: 14px; margin-top: 18px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        td { padding: 6px 0; vertical-align: top; }
        td.label { width: 190px; color: #64748b; }
        .qr { text-align: center; margin-top: 18px; }
        .qr img { width: 130px; height: 130px; }
        .footer { margin-top: 28px; border-top: 1px solid #cbd5e1; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>Scholarship Award Letter</h1>
    <p class="muted">Shiksha Sahayata — Government Scholarship Management System (Prototype)</p>

    <div class="box">
        <table>
            <tr>
                <td class="label">Award Number</td>
                <td><strong>{{ $award->award_number }}</strong></td>
            </tr>
            <tr>
                <td class="label">Scholarship</td>
                <td>{{ $application->scholarship->title }}</td>
            </tr>
            <tr>
                <td class="label">Recipient</td>
                <td>{{ $application->student->name }}</td>
            </tr>
            <tr>
                <td class="label">Student ID</td>
                <td>{{ $application->student->scholar_student_id }}</td>
            </tr>
            <tr>
                <td class="label">Application Reference</td>
                <td>{{ $application->id }}</td>
            </tr>
            <tr>
                <td class="label">Issued On</td>
                <td>{{ $award->issued_at?->format('j F Y') ?: '—' }}</td>
            </tr>
            <tr>
                <td class="label">Award Status</td>
                <td>{{ $award->status->label() }}</td>
            </tr>
            <tr>
                <td class="label">Disbursement Status</td>
                <td>{{ $award->disbursement_status->label() }}</td>
            </tr>
            <tr>
                <td class="label">Verification Code</td>
                <td>{{ $award->verification_code }}</td>
            </tr>
        </table>
    </div>

    <p style="margin-top: 18px;">
        This letter confirms that the recipient has been selected for the scholarship named above.
        Scan the QR code or visit the verification link to confirm that this award is genuine.
    </p>

    <div class="qr">
        <img src="{{ $qrDataUri }}" alt="Award verification QR code" />
        <p class="muted">{{ $verificationUrl }}</p>
    </div>

    <div class="footer muted">
        This is a prototype award letter generated by Shiksha Sahayata. It carries no monetary value and is not
        issued by any real government body.
    </div>
</body>
</html>
